# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false

# Minecraft / NeoForge Versions
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.76
neo_version_range=[26.1.2,)

# Mod Properties
mod_id=maidquest
mod_name=女仆委托
mod_version=0.0.1
mod_group_id=com.fennecmomo.maidquest
mod_license=MIT
